apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: kube-system
data:
  key: {{ ceph_user_token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: prod
data:
  key: {{ ceph_user_token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: release
data:
  key: {{ ceph_user_token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
data:
  key: {{ ceph_user_token }}
