---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prod
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prod-admin
subjects:
- kind: User
  name: {{ k8s_release_username }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: release
  namespace: release
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-admin
subjects:
- kind: User
  name: {{ k8s_release_username }}
