---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: default
data:
  tls.crt: {{ k8s_services_cert | b64encode }}
  tls.key: {{ k8s_services_cert_key | b64encode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: kube-system
data:
  tls.crt: {{ k8s_services_cert | b64encode }}
  tls.key: {{ k8s_services_cert_key | b64encode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: prod
data:
  tls.crt: {{ k8s_services_cert | b64encode }}
  tls.key: {{ k8s_services_cert_key | b64encode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: release
data:
  tls.crt: {{ k8s_services_cert | b64encode }}
  tls.key: {{ k8s_services_cert_key | b64encode }}
