---
# Conteiner Network Interface type, valid values: `calico`, `romana`
cni_type: calico

# Container Network Interface (CNI) bin path
cni_bin_dir: /opt/cni/bin

# Kubernetes services host names
k8s_services_name: services.your-domain-name

# Cockroach DB data dir
k8s_cockroachdb_dir: /var/lib/cockroachdb

# Cockroach DB volume and cache size
k8s_cockroachdb_volume_size: 1Gi
k8s_cockroachdb_cache_size: 250Mb

# Master hosts nsmes
k8s_master_hosts: {}

# Node hosts names
k8s_node_hosts: {}

# Cockroach DB images
k8s_cockroachdb_image: cockroachdb/cockroach
k8s_cockroachdb_image_tag: v1.0.1
k8s_cockroachdb_init_image: webdeva/cockroach-init
k8s_cockroachdb_init_image_tag: 0.0.2
