---

apiVersion: v1
kind: Service
metadata:
  name: servicegraph
  namespace: {{ k8s_istio_namespace }}
spec:
  ports:
  - name: http
    port: 8088
  selector:
    app: servicegraph

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: servicegraph
  namespace: {{ k8s_istio_namespace }}
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: ignore
      labels:
        app: servicegraph
    spec:
      containers:
      - name: servicegraph
        image: {{ k8s_istio_servicegraph_image }}:{{ k8s_istio_servicegraph_image_tag }}
        ports:
          - containerPort: 8088
        args:
        - --prometheusAddr=http://prometheus:9090
