---
- hosts: master
  remote_user: '{{ k8s_ssh_user }}'
  become: true

- hosts: master_lb
  remote_user: '{{ k8s_ssh_user }}'
  become: true
  roles:
    - role: haproxy
      k8s_master_hosts: '{{ groups["master"] }}'
