---
- hosts: node
  remote_user: '{{ k8s_ssh_user }}'
  become: true

- hosts: node_lb
  remote_user: '{{ k8s_ssh_user }}'
  become: true
  roles:
    - role: haproxy
      k8s_node_hosts: '{{ groups["node"] }}'
      haproxy_redirect_http: false
