---
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: fast
  provisioner: kubernetes.io/rbd
  parameters:
    monitors: {{ ceph_monitor_servers }}
    adminId: {{ ceph_user_name }}
    adminSecretName: ceph-secret
    adminSecretNamespace: kube-system
    pool: {{ ceph_pull_name }}
    userId: {{ ceph_user_name }}
    userSecretName: ceph-secret
