---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prod-admin
  namespace: prod
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: release-admin
  namespace: release
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
