---
# Flannel backend type (Options: gce, vxlan)
k8s_flannel_backend: vxlan

# Internal overlay network. It will assign IP
# addresses from this range to individual pods.
# This network must be unused block of space.
k8s_cluster_cidr: 10.20.0.0/16

# Calico version 
k8s_calico_version: 2.4.1

# Calico CTL version 
k8s_calicoctl_version: 1.4.0

# Kubernetes configs path
k8s_conf_dir: /etc/kubernetes

# Canal configs path
k8s_canal_dir: '{{ k8s_conf_dir }}/canal'

# Container Network Interface (CNI) bin & config path
cni_bin_dir: /opt/cni/bin
cni_conf_dir: '{{ k8s_conf_dir }}/cni/net.d'

# Executable files path
k8s_bin_dir: /usr/bin

# Master hosts nsmes
k8s_master_hosts: {}

# Flannel image
k8s_flannel_image: quay.io/coreos/flannel
k8s_flannel_image_tag: v0.8.0

# Calico images
k8s_calico_node_image: quay.io/calico/node
k8s_calico_node_image_tag: v{{ k8s_calico_version }}
k8s_calico_cni_image: quay.io/calico/cni
k8s_calico_cni_image_tag: v1.10.0
