- include: toolchain/setup.yml
- include: ssl/setup.yml
- include: ssl/master.yml
- include: ssl/build.yml
- include: cluster/etcd.yml
- include: cluster/master.yml
- include: cluster/node.yml
- include: cluster/canal.yml
- include: addons/setup.yml
